# Generated by Django 4.1.7 on 2023-08-17 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_company_alter_contact_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
