# Generated by Django 4.1.7 on 2023-08-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email * "),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Apellido"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile",
            field=models.CharField(max_length=12, verbose_name="Celular * "),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre * "),
        ),
    ]
