# Generated by Django 4.1.7 on 2023-08-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_alter_contact_email_alter_contact_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(
                blank=True, default="", max_length=30, null=True, verbose_name="Empresa"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Notas"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                null=True,
                verbose_name="Teléfono",
            ),
        ),
    ]
