# Generated by Django 4.1.7 on 2023-08-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0007_alter_contact_company_alter_contact_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Empresa"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Teléfono"
            ),
        ),
    ]
