# Generated by Django 4.1.7 on 2023-08-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="estimated_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha finalización estimada"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.IntegerField(default=3, verbose_name="Prioridad"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Título"),
        ),
    ]
