# Generated by Django 4.1.7 on 2023-08-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todo_description_alter_todo_estimated_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Título * "),
        ),
    ]
