# Generated by Django 4.1.7 on 2023-08-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="estimated_end",
            field=models.DateField(
                blank=True,
                default="",
                null=True,
                verbose_name="Fecha finalización estimada",
            ),
        ),
    ]
