# Generated by Django 4.1.7 on 2023-08-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_todo_description_alter_todo_estimated_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="estimated_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha finalización estimada"
            ),
        ),
    ]
